name: anywhere_mobile
description: Anywhere Mobile Candidate Coding Exercise
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  character_repository:
    path: packages/character_repository
  dartz: ^0.10.1
  dio: ^5.3.2
  easy_debounce: ^2.0.3
  fast_cached_network_image: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  http_mock_adapter: ^0.4.4

flutter:
  uses-material-design: true
