name: Anywhere Mobile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/anywhere_mobile_verify_and_test.yaml'
      - '**'
      - packages/character_repository/**
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/**'
      - '**'
      - packages/character_repository/**

jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.12.0
    with:
      working_directory: .
      min_coverage: 90
      flutter_channel: stable
      flutter_version: 3.10.0